const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const Module = require('node:module');
const ts = require('typescript');
const source = path.resolve(__dirname, '../lib/ads-analysis.ts');
const compiled = ts.transpileModule(fs.readFileSync(source, 'utf8'), { compilerOptions: { target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.CommonJS } }).outputText;
const m = new Module(source, module); m.filename = source; m.paths = module.paths; m._compile(compiled, source);
const a = m.exports;
const base = { date:'2026-09-18', account:'제주 계정', accountId:'a', campaign:'조회', campaignId:'c', creative:'금 매입', creativeId:'r', spend:10000, impressions:1000, clicks:20, conversions:2, revenue:30000 };
const pack = (rows, extra={}) => JSON.stringify({schema:'goldcheju.ads.v1', currency:'KRW', timezone:'Asia/Seoul', taxBasis:'included', ...extra, rows});
const parse = (rows,extra) => a.parseAdReport(pack(rows,extra));

test('valid JSON and exact weighted metrics', () => { const r = parse([base, {...base,date:'2026-09-17',spend:20000,impressions:9000,clicks:90,conversions:8,revenue:70000}]); const n=a.summarize(r.rows); assert.equal(n.spend,30000); assert.ok(Math.abs(n.ctr-1.1)<1e-12); assert.equal(n.cpc,30000/110); assert.equal(n.cpa,3000); assert.equal(n.roas,100000/30000*100); });
test('all true zero metrics remain zero, denominators yield null', () => { const n = a.summarize(parse([{...base,spend:0,impressions:0,clicks:0,conversions:0,revenue:0}]).rows); assert.equal(n.spend,0); assert.equal(n.conversions,0); assert.equal(n.revenue,0); assert.equal(n.ctr,null); assert.equal(n.cpc,null); assert.equal(n.cpa,null); assert.equal(n.roas,null); });
test('missing conversion or revenue is never treated as zero', () => {const n=a.summarize(parse([base,{...base,date:'2026-09-17',conversions:null,revenue:null}]).rows); assert.equal(n.conversions,null);assert.equal(n.revenue,null);assert.equal(n.cpa,null);assert.equal(n.roas,null);});
test('empty selection does not fabricate optional totals',()=>{const n=a.summarize([]);assert.equal(n.count,0);assert.equal(n.conversions,null);assert.equal(n.cpc,null);});
test('fenced JSON import',()=>assert.equal(a.parseAdReport('```json\n'+pack([base])+'\n```').rows.length,1));
test('JSON array import',()=>assert.equal(a.parseAdReport(JSON.stringify([base])).rows.length,1));
test('CSV Korean headers / quoted currency',()=>{const r=a.parseAdReport(a.CSV_HEADER+'2026-09-18,제주점,조회,금 매입,"10,000",1000,20,2,30000');assert.equal(r.rows[0].spend,10000);});
test('TSV spreadsheet paste',()=>{const r=a.parseAdReport('일자\t광고계정명\t캠페인명\t광고명\t소진 금액(원)\t노출 수\t클릭 수\n2026.9.18\t계정\t캠페인\t소재\t10,000원\t1,000\t20');assert.equal(r.rows[0].spend,10000);assert.equal(r.rows[0].conversions,null);});
test('quoted multiline creative name preserved',()=>{const r=a.parseAdReport(a.CSV_HEADER+`2026-09-18,제주점,조회,"금, ""목걸이""
매입",100,100,2,,`); assert.equal(r.rows[0].creative, '금, "목걸이"\n매입');});
test('BOM and CRLF supported',()=>assert.equal(a.parseAdReport('\uFEFF'+a.CSV_HEADER.replace('\n','\r\n')+'20260918,a,c,r,100,100,1,,\r\n').rows.length,1));
test('duplicate identical rows count once',()=>{const r=parse([base,base]);assert.equal(r.rows.length,1);assert.match(r.warnings.join(' '),/중복/);});
test('conflicting duplicates rejected',()=>assert.throws(()=>parse([base,{...base,spend:3}]),/서로 다른/));
test('different account ID not grouped',()=>{const r=parse([base,{...base,accountId:'b'}]);assert.equal(a.groupCreatives(r.rows).length,2);});
test('same creative name in distinct campaigns not merged',()=>{const r=parse([base,{...base,campaignId:'d'}]);assert.equal(a.groupCreatives(r.rows).length,2);});
test('daily ordering',()=>{const r=parse([{...base,date:'2026-09-18'},{...base,date:'2026-09-10'}]);assert.equal(r.rows[0].date,'2026-09-10');assert.equal(a.dailyMetrics(r.rows)[0].date,'2026-09-10');});
test('subtotal CSV row excluded explicitly',()=>{const r=a.parseAdReport(a.CSV_HEADER+'2026-09-18,a,c,r,100,100,1,,\n합계,,,,100,100,1,,');assert.equal(r.rows.length,1);assert.match(r.warnings.join(' '),/합계/);});
test('not enough columns rejected',()=>assert.throws(()=>a.parseAdReport(a.CSV_HEADER+'2026-09-18,a,c,r,10,000,100,1,0,0'),/열 개수/));
test('unclosed quotes rejected',()=>assert.throws(()=>a.readTable('a,b\n"c,d'),/따옴표/));
test('quote garbage rejected',()=>assert.throws(()=>a.readTable('a,b\n"c"d,e'),/따옴표/));
test('duplicate CSV headers rejected',()=>assert.throws(()=>a.parseAdReport('date,date\n2026-09-18,2026-09-18'),/중복/));
test('ambiguous alias mapping rejected',()=>assert.throws(()=>parse([{...base,cost:100}]),/중복 매핑/));
test('only header rejected',()=>assert.throws(()=>a.parseAdReport(a.CSV_HEADER),/데이터/));
test('empty array rejected',()=>assert.throws(()=>parse([]),/없어요/));
test('non object row rejected',()=>assert.throws(()=>parse([1]),/객체/));
test('campaign totals without creative rejected',()=>assert.throws(()=>parse([{...base,creative:''}]),/소재명/));
test('period aggregates without date rejected',()=>assert.throws(()=>parse([{...base,date:undefined}]),/날짜/));
test('impossible date rejected',()=>assert.throws(()=>parse([{...base,date:'2026-02-30'}]),/날짜/));
test('leap day accepted only in leap year',()=>{assert.equal(a.dateISO('2024-02-29'),'2024-02-29');assert.throws(()=>a.dateISO('2025-02-29'));});
test('negative values rejected',()=>assert.throws(()=>parse([{...base,spend:-100}]),/0 이상/));
test('invalid money formats not coerced',()=>{for(const spend of ['1만원','10%','=1+2','1,2',true,{},NaN,Infinity])assert.throws(()=>parse([{...base,spend}]));});
test('missing required zero not invented',()=>assert.throws(()=>parse([{...base,spend:''}]),/값이 없어요/));
test('integer clicks',()=>assert.throws(()=>parse([{...base,clicks:1.5}]),/정수/));
test('other currency rejected',()=>assert.throws(()=>parse([base],{currency:'USD'}),/KRW/));
test('timezone not silently reinterpreted',()=>assert.throws(()=>parse([base],{timezone:'UTC'}),/한국 시간/));
test('unsupported schema rejected',()=>assert.throws(()=>parse([base],{schema:'other'}),/지원하지/));
test('long name rejected',()=>assert.throws(()=>parse([{...base,creative:'x'.repeat(301)}]),/300/));
test('byte and row limit',()=>{assert.throws(()=>a.parseAdReport('가'.repeat(700000)),/2MB/);assert.throws(()=>parse(Array(5001).fill(base)),/5,000/);});
test('prior period nonoverlap and same inclusive length',()=>assert.deepEqual(a.previousPeriod('2026-09-12','2026-09-18'),{from:'2026-09-05',to:'2026-09-11',days:7}));
test('year crossover date',()=>assert.deepEqual(a.previousPeriod('2026-01-01','2026-01-07'),{from:'2025-12-25',to:'2025-12-31',days:7}));
test('bad range rejected',()=>{assert.throws(()=>a.previousPeriod('2026-09-18','2026-09-12'));assert.throws(()=>a.previousPeriod('2020-01-01','2026-09-12'));});
test('Seoul timezone not browser local',()=>assert.equal(a.seoulToday(new Date('2026-09-18T16:00:00Z')),'2026-09-19'));
test('change vs zero is unavailable not Infinity',()=>{assert.equal(a.changePercent(3,0),null);assert.equal(a.changePercent(null,5),null);assert.equal(a.changePercent(0,10),-100);});
test('account/campaign/date filtering',()=>{const r=parse([base,{...base,date:'2026-09-17',accountId:'b'}]);assert.equal(a.selectRows(r.rows,'2026-09-18','2026-09-18','a').length,1);assert.equal(a.selectRows(r.rows,'2026-09-01','2026-09-02').length,0);});
test('JSON export and restore preserves metrics',()=>{const r=parse([base]);const next=a.parseAdReport(a.reportJSON(r));assert.deepEqual(next.rows,r.rows);assert.equal(next.taxBasis,'included');});
test('MCP prompt asks for real data only and never writes',()=>{const p=a.buildAdsPrompt('test','2026-09-12','2026-09-18');assert.match(p,/읽기 전용/);assert.match(p,/절대 실행하지 마/);assert.match(p,/미제공 시 null/);assert.match(p,/2026-09-05/);assert.match(p,/완료|페이지/);});
test('missing source ID and partial report warn',()=>{const r=parse([{...base,accountId:'',creativeId:'',revenue:null}],{complete:false});assert.match(r.warnings.join(' '),/일부 데이터/);assert.match(r.warnings.join(' '),/ID/);});
test('demo is explicitly marked',()=>{const r=a.demoReport('2026-09-19');assert.equal(r.demo,true);assert.equal(r.rows.length,28);assert.match(a.reportText(r,r.rows,'2026-09-05','2026-09-18'),/실제 광고 아님/);});
test('no causal or profitability assertion from missing conversions',()=>{const r=parse([{...base,conversions:null,revenue:null}]);assert.match(a.observations(r.rows).join(' '),/판단하지 않았어요/);});
test('0 conversions is distinct from missing tracking',()=>{const r=parse([{...base,conversions:0}]);assert.match(a.observations(r.rows).join(' '),/전환이 0/);});

test('dated subtotal rows not double-counted',()=>{const r=parse([base,{...base,creative:'합계',creativeId:'total'}]);assert.equal(r.rows.length,1);});
test('row currency rejected even if top level says KRW',()=>assert.throws(()=>parse([{...base,currency:'USD'}]),/KRW/));
test('incomplete report flag survives save/restore',()=>{const r=parse([base],{complete:false});assert.equal(a.parseAdReport(a.reportJSON(r)).complete,false);});
test('empty summary says no data rather than zero',()=>assert.match(a.reportText(parse([base]),[],'2026-09-01','2026-09-02'),/성과를 계산하지 않았습니다/));
